import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DialogProvider from "../context/DialogContext";
import Toolbar from "./components/GToolbar/GToolbar";
import { UserProvider } from "../context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJs_13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DialogProvider>
          <UserProvider>
            <Toolbar />
            {children}
          </UserProvider>
        </DialogProvider>
      </body>
    </html>
  );
}
